### ISSUE TITLE
Can't Installation

### ISSUE THREAD

**Issue by ahmadrifaiii** [ingeniasoftware/luthier-ci#19]
i have a problem
`
A PHP Error was encountered

Severity: Error

Message: Class 'Luthier\Hook' not found

Filename: config/hooks.php

Line Number: 5

Backtrace:
`
![image](https://user-images.githubusercontent.com/8164160/42730508-ef515f3c-881f-11e8-9428-f91bd8724405.png)

**Comment by andersonsalas** [comment]
Hi @83rifai!

Seems to be a problem with the composer autoload. Please provide the following information:

1. PHP / OS / CodeIgniter version
2. Value of `$config['composer_autoload']` variable (in `application/config/config.php` file)

**Comment by maniix123** [comment]
@83rifai
just set `$config['composer_autoload'] = 'vendor/autoload.php';` 
at `application\config\config.php`. The documentation doesn't even state that. It just says to set it into `TRUE`

**Comment by andersonsalas** [comment]
@putanginamogiegy ~~~set the `$config['composer_autoload']` to `TRUE` has the same behaviour that the `'vendor/autoload.php'` string because~~~ that's the default `vendor` folder location, unless you're doing something custom:

https://github.com/bcit-ci/CodeIgniter/blob/master/system/core/CodeIgniter.php#L168-L175

EDIT: I've done some tests and the value  `vendor/autoload.php` will NOT work because CodeIgniter expects an absolute path here. You can prefix the string with the `APPPATH` constant, of course, but it's the same what using the `TRUE` value:

 ```
// Wrong, must be an absolute path:
$config['composer_autoload'] =  'vendor/autoload.php';  
// OK, absolute path:
$config['composer_autoload'] =  APPPATH . '/vendor/autoload.php';  
// The same of above:
$config['composer_autoload'] =  TRUE; 
```

**Comment by abmcr** [comment]
for my application this 

`$config['composer_autoload'] =  './vendor/autoload.php';`

solve the problem

**Comment by masoud005** [comment]
i have the same problem 
checked what you said above,all are correct
but the same error appears
phpversion: 5.6.31
ci_version: 3.0-dev

also tested on CI 3.1.10 version

**Comment by andersonsalas** [comment]
> i have the same problem
> checked what you said above,all are correct
> but the same error appears
> phpversion: 5.6.31
> ci_version: 3.0-dev
> also tested on CI 3.1.10 version

Hi @masoud005! 😄 

Please open a new issue in order to bring you better support. This is a pretty old one.

Thanks for using Luthier CI.
