### ISSUE TITLE
route get with parameter

### ISSUE THREAD

**Issue by haruhinoshana** [ingeniasoftware/luthier-ci#4]
hi sir can i ask how to make a route on get with parameter like 
ex: welcome/(:any) 

thank you

**Comment by andersonsalas** [comment]
Hi!

Just enclose it in curly brackets like `{this}`

```php
Route::get('author/{slug}', ['uses' => 'blog@author', 'as' => 'posts-by-author']);   
//  {slug} => (:any)
```

Available parameters definitions:

```
// 1. Anything
// {any: [name]} or simply:
// {[name]}
// Example: {any:foo}, {foo}

// 2. Numeric 
// {num:[name]} 
// Example: {num:bar}

// 3. Custom regex
// {[regex]:[name]}
// Example: '{([0-9]{4}):year}/{([0-9]{2}):month}/{([0-9]{2}):day}'  
```

**Comment by robertsanseries** [comment]
@andersonsalas please add this in the documentation!

**Comment by andersonsalas** [comment]
@robertsanseries that syntax was changed a little bit since the issue date. The current syntax is [described](https://github.com/ingeniasoftware/luthier-ci#usage) in the `readme.md` file, and the complete documentation can be founded [here (english)](https://luthier-ci.ingenia.me/en/docs/routes#parameters) and [here (spanish)](https://luthier-ci.ingenia.me/es/docs/routes#parameters)
