### ISSUE TITLE
Override Package Classes

### ISSUE THREAD

**Issue by giorgosstab** [ingeniasoftware/luthier-ci#47]
hey mate..nice work about your package..but i am curious if i can ovveride some of your controller and add mine logic without edit vendor/luthier/luthier/src

**Comment by andersonsalas** [comment]
Hi @giorgosstab,

What kind of logic/files do you want to extend? Editing vendor files is a bad idea because you will lose any changes when update the package with composer.

**Comment by giorgosstab** [comment]
thanks for your quick reply! i wanna extend cli mingrate template file file path: luthier/luthier/src/Cli.php

**Comment by andersonsalas** [comment]
I have done some tests and unfortunately there is no way to extend the `Luthier\Cli` class (without doing bad practices) due CodeIgniter limitations. Even without that limitations, the base class contains only private methods, so no inheritance are available.

The good news: in this case there is no problem if you write your own Cli controller and copy the code of `Luthier\Cli` within your custom methods, since the original methods has no dependences but the `get_instance()` function (as `ci()`)

```php
<?php
# application/routes/cli.php

Luthier\Cli::maker();
Luthier\Cli::migrations();

// luthier make custom-controller [name]
Route::cli('luthier/make/custom-controller/{(.+):name}', 'MyCliController@makeController');

// luthier make custom-migration [name] [type?]
Route::cli('luthier/make/custom-migration/{name}/{((sequential|timestamp)):type?}', 'MyCliController@makeMigration');
```
And the controller:

```php
<?php

defined('BASEPATH') OR exit('No direct script access allowed');

class MyCliController extends CI_Controller
{
    public function __construct()
    {
        parent::__construct();
    }

    public function makeController($name)
    {
        echo 'Command "luthier make custom-controller" executed!';
        /* Original code here */
    }


    public function makeMigration($name, $type = 'timestamp')
    {
        echo 'Command "luthier make custom-migration" executed!';
        /* Original code here */
    }
}
```

Sorry about that limitation, CI 3 is an old-school framework and some OOP features such namespaces are missing. Hope this helps you, happy codding! :smiley:

**Comment by giorgosstab** [comment]
Thank you mate..i think i can make my work with that changes.. happy coding too! :D
